########################################################
# Ver：version 1.0
# ps: _config.yml
##########################################################

# html lang
title: Lusk.co
subtitle: "A fast, simple & powerful blog framework powered by Hexo (Node.js)."
description: "Lusk.co is a personal webserver"
author: Cody Lusk
language: en
timezone: America/Toronto

# main menu navigation
#menu:
#  Home : /
# Archives : /archives
# About : /about   # 默认使用主页的about风格,所以先注释掉 #

# stylesheets loaded in the <head>
stylesheets:
- /css/legend.css
- /css/contact-form.css

# scripts loaded in the end of the body
scripts:
- /js/legend.js
- /js/contact-form.js
- /js/classie.js

##########################################################################
####(最外层_config.yml)修改的参数 
# url: http://yoursite.com 改为你自己博客的网站，如我的：url: https://ihongren.github.io
# per_page: 10 由于本主题归档页不分页，所以改为 per_page: 0 
# theme: 添加本主题 theme: legend ，请确保本主题文件在theme目录下
####################################################################################

# Comments Intergration (LiveRe)
#livere_uid: MTAyMC8yOTI2MS81ODI5

# donate 
#wechatpay: /images/wechatpay.png
#alipay:  /images/alipay.png
#reward_comment: 文章对我有帮助，打赏作者



# Links
social:
  Github: 
    url: https://github.com/ChaosZero112
    icon: /images/github.png
  LinkedIn:
    url: https://www.linkedin.com/in/cody-lusk-97b48b52/
    icon: /images/linkedin.png
#  Fackbook: 
#    url: https://facebook.com
#    icon: /images/facebook.png
#  Twitter:
#   url: https://twitter.com/ihongren
#   icon: /images/twitter.png

##############################################################
# Miscelaneous
favicon: /favicon.ico

# RSS订阅
#plugin:
#- hexo-generator-feed
#subnav:
#rss: /atom.xml
#rss_icon: /images/rss.png

# Feed Atom
#feed:
#type: atom
#path: atom

# Theme colors
theme_color: '#3885bc'  #尝试替换自己喜欢的颜色 '#2ca6cb'... #
theme_highlight_color: '#4400B3' # '#00bfff'... #

# 代码主题 目前添加了两种: tomorrow.css | tomorrow-night.css  
# 想要尝试更多请移步: https://jmblog.github.io/color-themes-for-google-code-prettify/ #
code_theme: /plugins/code-theme/tomorrow.css

# Font (header,footer...)
theme_font_family: Microsoft Yahei

# Background
home_video: 
  src: "http://cdn.calm.com/scenes/scene-Qqkzy9k7Eo.mp4?v=1418162238190"
  show: true
  bgimage: /images/background.png

# Audio
audio_src: "http://cdn.calm.com/scenes/scene-Qqkzy9k7Eo.m4a?v=1418162240715"

# Audio on Home
home_audio: false

# Audio on Posts
post_audio: false

# Static bg image #
home_bgimage: /images/background.png

# 关于页面设置，怎么生成关于页面? 命令:$ hexo new page "about"" #
#提供两种选择: 默认是第一种(home_about)
#1.home_about:在主页显示关于我
#2.menu_about:在菜单栏新开一个菜单"关于", 请确保菜单配置menu，添加了about项(打开上面menu,about的注释)
about_type: home_about
    
